<?php

define('IMPORTED_NONE',0);
define('IMPORTED_STORY',1);
define('IMPORTED_STORY_CHAPTER',2);

function thuypx_import_menu() {
    $items['thuypx_import/product'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => 'thuypx_import_product',
        'access arguments' => array('access content'),
    );
    $items['thuypx_import/replacedomain'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => 'thuypx_import_replacedomain',
        'access arguments' => array('access content'),
    );
    return $items;
}

function thuypx_import_product() {

    include 'lib.php';
    $csv = new parseCSV();
    $csv->auto('F:\Downloads\data-news.csv');
    $d=node_load(17);
    $j=0;
    foreach($csv->data as $row){
        $j++;
        $node = new stdClass();
        $node->title = $row['tieude'];
        $node->type = "article";
        node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
        $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
        $node->uid = 1;
        $node->status = 1; //(1 or 0): published or not
        $node->promote = 0; //(1 or 0): promoted to front page
        $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write
        #category
        if($row['loai']){
            $term1=taxonomy_get_term_by_name($row['loai'],'news_category');
            if(count($term1)<1){
                $term1 = new stdClass();
                $term1->name = $row['loai'];
                $term1->vid = 4;
                taxonomy_term_save($term1);
            }else{
                $term1=array_shift($term1);
            }
        }

        $node->field_news_category[LANGUAGE_NONE][0]['tid']=$term1->tid;

        #image
        $existing_filepath = 'F:\websites\HOANGNGAN-VN\data_store\upload'.DIRECTORY_SEPARATOR.$row['hinhanh'];
        if($row['hinhanh'] && file_exists($existing_filepath)){
            $new_filepath = "public://{$row['hinhanh']}";
            $drupal_file = file_save_data(file_get_contents($existing_filepath), $new_filepath);
            $drupal_file->alt = $node->title;
            $drupal_file->title = $node->title;
            $node->field_image[$node->language][0] = get_object_vars($drupal_file);
        };

//summary

        $node->field_summary[$node->language][0]['format']  = 'full_html';
        $node->field_summary[$node->language][0]['value']  = $row['mota'];

        $node->body[LANGUAGE_NONE][0]['format']  = 'full_html';
        $node->body[LANGUAGE_NONE][0]['value']  = $row['noidung'];



        $node->metatags[LANGUAGE_NONE]['title']['value'] = $row['title'];
        $node->metatags[LANGUAGE_NONE]['keywords']['value'] = $row['keyword'];
        $node->metatags[LANGUAGE_NONE]['description']['value'] = $row['de'];

        $node = node_submit($node); // Prepare node for saving
        node_save($node);

    }

}

function thuypx_import_replacedomain(){
    // Return all nids of nodes of type "page".
    $nids = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->fields('n', array('type'))
        ->condition('n.type', 'product')
        ->execute()
        ->fetchCol(); // returns an indexed array

// Now return the node objects.
    $nodes = node_load_multiple($nids);

    foreach($nodes as $node){

        $body=$node->body[LANGUAGE_NONE][0]['value'];
        $node->body[LANGUAGE_NONE][0]['value']=str_replace('http://maylocnuocviet.com/data_store/anhdaidien/','/sites/default/files/',$body);
        node_save($node);
    }

}
